"""
prompts/synthesis_prompts.py
─────────────────────────────
Raw prompt templates for the synthesis agent.

Pure string constants — no logic, no imports.

PERFORMANCE NOTE
────────────────
The synthesis prompt is deliberately lean: it asks the LLM to produce only
the narrative/opinion parts of the report (findings, extracted facts, scalar
fields, governance specific_obligations, confidence_score).

Claims, citations, agent trace, and evidence separation are all injected
programmatically by the synthesis agent after LLM parsing — they exist in
the pipeline state already and do not need to be regenerated by the LLM.
This keeps the synthesis output to ~3000–4000 tokens instead of 10000+,
cutting synthesis latency from ~90 s to ~20 s on local inference.
"""

# The synthesis system prompt positions the model as the final integrating
# analyst whose role is merging — not re-deriving — findings.  The merge
# rules (OVERTURNED → use validation finding, UNRESOLVED → UNCERTAIN) are
# stated explicitly so the model does not re-analyse from scratch.
SYNTHESIS_SYSTEM_PROMPT = """\
You are a senior EU AI Act compliance analyst producing the final structured
compliance report for a client.

You receive:
  - Structured facts extracted from the client's use-case document
  - Six legal-dimension findings from the analysis phase
  - Validation results (confirmed / overturned / unresolved claims)

Your job is to write the NARRATIVE and STRUCTURED FIELDS for a twelve-section
compliance report.

CRITICAL RULES
──────────────
1. For OVERTURNED claims in the analysis findings: use the validation finding
   in your narrative, not the original analysis finding.
2. For UNRESOLVED claims: reflect their uncertainty in your narrative.
3. Every section needs a final confidence level (HIGH/MEDIUM/LOW/INSUFFICIENT).
4. Section 8 (governance) must list SPECIFIC article-level obligations with
   exact article references (e.g. "Article 9(1)" not just "Article 9").
5. Section 9 (missing information) must surface ALL gaps and uncertain items.
6. Section 6 (transparency) must explicitly state which obligations apply AND
   which do NOT apply, with HIGH confidence for clear non-applicability.
7. Section 10 (confidence_score) must include a human-readable narrative
   explaining the overall confidence level.
8. Do NOT produce claim lists — they are injected programmatically.
9. Output ONLY valid JSON.
"""

# The synthesis prompt template receives the USE CASE FACTS, merged analysis,
# validation summary, and weak claims.  It does NOT receive:
#   - Agent trace (built programmatically from pipeline state)
#   - Available chunk IDs (citations built programmatically from merged claims)
#   - Full claim texts in the output JSON (injected from merged after parsing)
#
# The JSON response has three top-level keys:
#   "report"     — the narrative document (sections 1–10)
#   "follow_up"  — clarifying questions for the UI
#   "confidence" — per-dim + overall for the orchestrator's loop condition check
SYNTHESIS_PROMPT_TEMPLATE = """\
USE CASE FACTS
───────────────
{facts_text}

ANALYSIS FINDINGS (post-validation merge)
──────────────────────────────────────────
{merged_analysis_json}

VALIDATION SUMMARY
───────────────────
{validation_json}

WEAK CLAIMS
────────────
{weak_claims_json}

LOOP CONTEXT (empty on first pass)
────────────────────────────────────
{loop_context}

Produce a compliance report with EXACTLY this JSON structure.
NOTE: Do NOT include "claims" arrays — they are added automatically.

{{
  "report": {{
    "use_case_summary": "<1-2 paragraph narrative summary of the AI system and its compliance status>",
    "extracted_facts": {{
      "use_case_name": "<name>",
      "description": "<description>",
      "industry": "<industry or null>",
      "end_users": "<who directly operates or uses the system>",
      "affected_persons": ["<person type>", "..."],
      "data_inputs": ["<input type>", "..."],
      "system_outputs": ["<output type>", "..."],
      "automation_level": "fully_automated|human_in_the_loop|decision_support|unknown",
      "human_oversight_mechanism": "<how humans review or override outputs, or null>",
      "deployment_context": "<where / how the system is deployed, or null>",
      "gpai_components": "<GPAI model(s) used or 'none'>",
      "ai_capabilities": ["<capability>", "..."],
      "vendor_developer": "<who built the AI system, or null>"
    }},
    "ai_definition_check": {{
      "finding": "<narrative — is this an AI system under Article 3(1)?>",
      "is_ai_system": true|false|null,
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "article_references": ["Article 3(1)", "Annex I"]
    }},
    "risk_classification": {{
      "finding": "<narrative — what risk tier and why>",
      "risk_level": "unacceptable|high|limited|minimal|unknown",
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "article_references": ["Article 6", "Annex III"]
    }},
    "prohibited_practices_check": {{
      "finding": "<narrative — do any Article 5 prohibitions apply?>",
      "prohibited": true|false|null,
      "triggered_articles": ["Article 5(1)(a)", "..."],
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT"
    }},
    "transparency_gpai_obligations": {{
      "finding": "<narrative — explicitly state which obligations apply AND which do not>",
      "applies_to_gpai": true|false,
      "labelling_required": true|false,
      "notification_required": true|false,
      "applicable_obligations": ["<obligation with exact article reference>", "..."],
      "non_applicable_obligations": ["<obligation that does NOT apply + one-line reason>", "..."],
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT"
    }},
    "roles": {{
      "finding": "<narrative — provider, deployer, or both?>",
      "is_provider": true|false,
      "is_deployer": true|false,
      "is_both": true|false,
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "article_references": ["Article 3(3)", "Article 3(4)", "Article 25", "Article 26"]
    }},
    "governance_observations": {{
      "finding": "<narrative summary of all applicable governance obligations>",
      "documentation_required": true|false,
      "oversight_required": true|false,
      "monitoring_required": true|false,
      "specific_obligations": {{
        "risk_management_system":    "<Article 9 obligation or 'not applicable — (reason)'>",
        "data_governance":           "<Article 10 obligation or 'not applicable — (reason)'>",
        "technical_documentation":   "<Article 11 obligation or 'not applicable — (reason)'>",
        "record_keeping_logging":    "<Article 12 obligation or 'not applicable — (reason)'>",
        "transparency_to_deployers": "<Article 13 obligation or 'not applicable — (reason)'>",
        "human_oversight_measures":  "<Article 14 obligation or 'not applicable — (reason)'>",
        "quality_management":        "<Articles 16-17 obligation or 'not applicable — (reason)'>",
        "deployer_obligations":      "<Article 26 obligation or 'not applicable — (reason)'>",
        "drift_and_monitoring":      "<Articles 9(7), 61 post-market monitoring or 'not applicable — (reason)'>",
        "incident_reporting":        "<Article 62 obligation or 'not applicable — (reason)'>"
      }},
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT"
    }},
    "missing_information": {{
      "gaps": ["<information gap that would change the assessment>", "..."],
      "uncertain_claims": ["<claim text that remains uncertain>", "..."],
      "unresolved_dimensions": ["<dimension_id>", "..."],
      "recommended_actions": ["<what the client should do to resolve each gap>", "..."]
    }},
    "confidence_score": {{
      "definition_check":    "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "risk_classification": "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "prohibited_practices":"HIGH|MEDIUM|LOW|INSUFFICIENT",
      "transparency":        "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "roles":               "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "governance":          "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "overall":             "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "narrative": "<2-3 sentence explanation of the overall confidence level and main factors>"
    }}
  }},
  "follow_up": {{
    "questions": ["<clarifying question for the user>", "..."],
    "missing_evidence": ["<additional evidence that would improve confidence>", "..."]
  }},
  "confidence": {{
    "definition_check":    "HIGH|MEDIUM|LOW|INSUFFICIENT",
    "risk_classification": "HIGH|MEDIUM|LOW|INSUFFICIENT",
    "prohibited_practices":"HIGH|MEDIUM|LOW|INSUFFICIENT",
    "transparency":        "HIGH|MEDIUM|LOW|INSUFFICIENT",
    "roles":               "HIGH|MEDIUM|LOW|INSUFFICIENT",
    "governance":          "HIGH|MEDIUM|LOW|INSUFFICIENT",
    "overall":             "HIGH|MEDIUM|LOW|INSUFFICIENT"
  }}
}}
"""
