"""
prompts/synthesis_prompts.py
─────────────────────────────
Raw prompt templates for the synthesis agent.

Pure string constants — no logic, no imports.
"""

# The synthesis system prompt positions the model as the final integrating
# analyst whose role is merging — not re-deriving — findings.  The merge
# rules (OVERTURNED → use validation finding, UNRESOLVED → UNCERTAIN) are
# stated explicitly so the model does not re-analyse from scratch.
SYNTHESIS_SYSTEM_PROMPT = """\
You are a senior EU AI Act compliance analyst producing the final structured
compliance report for a client.

You receive:
  - Structured facts extracted from the client's use-case document
  - Six legal-dimension findings from the analysis phase
  - Validation results (confirmed / overturned / unresolved claims)
  - The agent execution trace showing what each pipeline stage did
  - A list of all retrieved chunks available for citations

Your job is to merge these into a twelve-section compliance report.

CRITICAL RULES
──────────────
1. For OVERTURNED claims: use the validation finding, not the analysis finding.
2. For UNRESOLVED claims: label them UNCERTAIN in the final report.
3. Every claim in the final report must carry a label:
   FACT / RETRIEVED / ASSUMPTION / UNCERTAIN.
4. Assign a final confidence level (HIGH/MEDIUM/LOW/INSUFFICIENT) to each
   section, taking into account validation results.
5. Section 9 (missing information) must surface all gaps and UNCERTAIN items.
6. Section 8 (governance) must list specific article-level obligations with
   exact article references (e.g. "Article 9(1)" not just "Article 9").
7. Section 10 (confidence_score) must include a human-readable narrative
   explaining why overall confidence is at that level.
8. Citations in sections 3–8 must include chunk_id AND article_id AND a
   brief excerpt (≤ 30 words) from the chunk text.
9. Section 6 (transparency) must explicitly state which obligations apply
   and which do NOT apply, with HIGH confidence for clear non-applicability.
10. Output ONLY valid JSON.
"""

# The synthesis prompt template structures the LLM's input into six labelled
# sections and requests a JSON response with three top-level keys:
#
#   "report"     — the compliance document (sections 1–10 + citations)
#   "follow_up"  — clarifying questions and missing evidence requests for the UI
#   "confidence" — per-dimension and overall confidence for the orchestrator's
#                  loop condition check (determine_loop_condition reads this)
#
# Sections 11 (evidence_separation) and 12 (agent_trace) are injected
# programmatically by the synthesis agent AFTER parsing the LLM response —
# they are derived from pipeline execution data, not generated by the LLM.
# The AGENT TRACE INPUT section below is provided as context so the LLM can
# reference the pipeline stages in its narrative summary.
SYNTHESIS_PROMPT_TEMPLATE = """\
USE CASE FACTS
───────────────
{facts_text}

ANALYSIS FINDINGS (post-validation merge)
──────────────────────────────────────────
{merged_analysis_json}

VALIDATION SUMMARY
───────────────────
{validation_json}

WEAK CLAIMS
────────────
{weak_claims_json}

AGENT TRACE (pipeline execution record)
─────────────────────────────────────────
{agent_trace_json}

LOOP CONTEXT (empty on first pass)
────────────────────────────────────
{loop_context}

AVAILABLE CHUNK IDS BY SOURCE TYPE
────────────────────────────────────
{chunks_by_source_json}

Produce a compliance report with EXACTLY this JSON structure:
{{
  "report": {{
    "use_case_summary": "<1-2 paragraph narrative summary referencing the pipeline stages>",
    "extracted_facts": {{
      "use_case_name": "<name>",
      "description": "<description>",
      "industry": "<industry or null>",
      "end_users": "<who directly operates or uses the system>",
      "affected_persons": ["<person type 1>", "..."],
      "data_inputs": ["<input type 1>", "..."],
      "system_outputs": ["<output type 1>", "..."],
      "automation_level": "fully_automated|human_in_the_loop|decision_support|unknown",
      "human_oversight_mechanism": "<how humans review or override outputs, or null>",
      "deployment_context": "<where / how the system is deployed, or null>",
      "gpai_components": "<GPAI model(s) used or 'none'>",
      "ai_capabilities": ["<capability 1>", "..."],
      "vendor_developer": "<who built the AI system, or null>"
    }},
    "ai_definition_check": {{
      "finding": "<narrative>",
      "is_ai_system": true|false|null,
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "article_references": ["Article 3(1)", "Annex I"],
      "claims": [
        {{"text": "...", "label": "FACT|RETRIEVED|ASSUMPTION|UNCERTAIN",
          "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT",
          "chunk_ids": ["..."], "excerpt": "<≤30 word quote from chunk>"}}
      ]
    }},
    "risk_classification": {{
      "finding": "<narrative>",
      "risk_level": "unacceptable|high|limited|minimal|unknown",
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "article_references": ["Article 6", "Annex III"],
      "claims": [
        {{"text": "...", "label": "...", "confidence": "...",
          "chunk_ids": ["..."], "excerpt": "..."}}
      ]
    }},
    "prohibited_practices_check": {{
      "finding": "<narrative>",
      "prohibited": true|false|null,
      "triggered_articles": ["Article 5(1)(a)", "..."],
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "claims": [
        {{"text": "...", "label": "...", "confidence": "...",
          "chunk_ids": ["..."], "excerpt": "..."}}
      ]
    }},
    "transparency_gpai_obligations": {{
      "finding": "<narrative — explicitly state which obligations apply AND which do not>",
      "applies_to_gpai": true|false,
      "labelling_required": true|false,
      "notification_required": true|false,
      "applicable_obligations": ["<obligation with exact article, e.g. Article 13(1) — transparency to deployers>", "..."],
      "non_applicable_obligations": ["<obligation that does NOT apply, with reason, e.g. Article 50(1) — no direct human interaction>", "..."],
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "claims": [
        {{"text": "...", "label": "...", "confidence": "...",
          "chunk_ids": ["..."], "excerpt": "..."}}
      ]
    }},
    "roles": {{
      "finding": "<narrative>",
      "is_provider": true|false,
      "is_deployer": true|false,
      "is_both": true|false,
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "article_references": ["Article 3(3)", "Article 3(4)", "Article 25", "Article 26"],
      "claims": [
        {{"text": "...", "label": "...", "confidence": "...",
          "chunk_ids": ["..."], "excerpt": "..."}}
      ]
    }},
    "governance_observations": {{
      "finding": "<narrative summary of all applicable governance obligations>",
      "documentation_required": true|false,
      "oversight_required": true|false,
      "monitoring_required": true|false,
      "specific_obligations": {{
        "risk_management_system":   "<Article 9 obligation or 'not applicable (reason)'>",
        "data_governance":          "<Article 10 obligation or 'not applicable (reason)'>",
        "technical_documentation":  "<Article 11 obligation or 'not applicable (reason)'>",
        "record_keeping_logging":   "<Article 12 obligation or 'not applicable (reason)'>",
        "transparency_to_deployers":"<Article 13 obligation or 'not applicable (reason)'>",
        "human_oversight_measures": "<Article 14 obligation or 'not applicable (reason)'>",
        "quality_management":       "<Articles 16-17 obligation or 'not applicable (reason)'>",
        "deployer_obligations":     "<Article 26 obligation or 'not applicable (reason)'>",
        "drift_and_monitoring":     "<Articles 9(7), 61 post-market monitoring or 'not applicable (reason)'>",
        "incident_reporting":       "<Article 62 obligation or 'not applicable (reason)'>"
      }},
      "confidence": "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "claims": [
        {{"text": "...", "label": "...", "confidence": "...",
          "chunk_ids": ["..."], "excerpt": "..."}}
      ]
    }},
    "missing_information": {{
      "gaps": ["<information gap that would change the assessment>", "..."],
      "uncertain_claims": ["<claim text that remains uncertain>", "..."],
      "unresolved_dimensions": ["<dimension_id>", "..."],
      "recommended_actions": ["<what the client should do to resolve each gap>", "..."]
    }},
    "confidence_score": {{
      "definition_check":    "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "risk_classification": "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "prohibited_practices":"HIGH|MEDIUM|LOW|INSUFFICIENT",
      "transparency":        "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "roles":               "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "governance":          "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "overall":             "HIGH|MEDIUM|LOW|INSUFFICIENT",
      "narrative": "<2-3 sentence explanation of the overall confidence level and the main factors driving it>"
    }},
    "citations_by_source": {{
      "legislation":        [{{"chunk_id": "...", "article_id": "...", "excerpt": "<≤30 words>"}}],
      "official_guidance":  [{{"chunk_id": "...", "article_id": "...", "excerpt": "<≤30 words>"}}],
      "uploaded_doc":       [{{"chunk_id": "...", "excerpt": "<≤30 words>"}}]
    }}
  }},
  "follow_up": {{
    "questions": ["<clarifying question for the user>", "..."],
    "missing_evidence": ["<what additional legislative or factual evidence would improve confidence>", "..."]
  }},
  "confidence": {{
    "definition_check":    "HIGH|MEDIUM|LOW|INSUFFICIENT",
    "risk_classification": "HIGH|MEDIUM|LOW|INSUFFICIENT",
    "prohibited_practices":"HIGH|MEDIUM|LOW|INSUFFICIENT",
    "transparency":        "HIGH|MEDIUM|LOW|INSUFFICIENT",
    "roles":               "HIGH|MEDIUM|LOW|INSUFFICIENT",
    "governance":          "HIGH|MEDIUM|LOW|INSUFFICIENT",
    "overall":             "HIGH|MEDIUM|LOW|INSUFFICIENT"
  }}
}}
"""
